project_name: "DDPM-testing"
model_cfg:
  in_channels: 3
  out_channels: 3
  channels: 192
  n_res_blocks: 3
  attention_levels: [1, 2]
  channel_multipliers: [1, 2, 3]
  channels_per_head: 64
  tf_layers: 2
  t_max: 1000
training_cfg:
  batch_size: 2048
  max_steps: 10000
  log_interval: 100
  checkpoint_pth: "checkpoint.pth"
  min_lr: 4e-4
  learning_rate: 4e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-8
  grad_norm: 1.0
  schedule_name: "cosine"
  warmup_prop: 0.05