project_name: "DDPM-testing"
model_cfg:
  in_channels: 3
  out_channels: 3
  channels: 128
  n_res_blocks: 2
  attention_levels: [0, 1]
  channel_multipliers: [1, 2, 2]
  channels_per_head: 32
  tf_layers: 2
  t_max: 1000
training_cfg:
  batch_size: 64
  max_steps: 10000
  log_interval: 100
  checkpoint_pth: "checkpoint.pth"
  learning_rate: 0.0001
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-8
  scheduler_lambda: 0.999